# Generated by Django 2.2.2 on 2019-06-27 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDespesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da Categoria', max_length=60, verbose_name='Nome')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('descricao', models.TextField(help_text='Uma Breve Descrição da Categoria', verbose_name='Descrição')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
        ),
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Titulo da Dispesa', max_length=60, verbose_name='Nome')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('data', models.DateField(blank=True, help_text='Data Do Pagamento', null=True, verbose_name='Data do Pagamento ex: 20/05/2019')),
                ('descricao', models.TextField(blank=True, help_text='Descrição', null=True, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
                ('estado', models.CharField(choices=[('Nao', 'Não Pago'), ('Pago', 'PAGO')], default='Pago', max_length=1, verbose_name='Estado')),
                ('doc', models.ImageField(blank=True, null=True, upload_to='docs/%Y-%m-%d', verbose_name='Imagens')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='despesa.CategoriaDespesa', verbose_name='Categoria da Despesa')),
                ('usuario', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
