# Generated by Django 2.2.2 on 2019-06-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriadespesa',
            name='descricao',
            field=models.TextField(blank=True, help_text='Uma Breve Descrição da Categoria', null=True, verbose_name='Descrição'),
        ),
    ]
