# Generated by Django 2.2.2 on 2019-06-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormaDePagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Dinheiro Cartão Etc', max_length=100, verbose_name='Forma de Pagamento')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Uma Breve Descrição ', null=True, verbose_name='Descrição')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receita_nome', models.CharField(help_text='Nome da Receita', max_length=100, verbose_name='Nome da Receita')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Uma Breve Descrição da Receita', null=True, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor Total da Receita', max_digits=8, verbose_name='Valor')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
        ),
    ]
